-- Base dataset for RLS experiments.
-- Tenant context travels in a session setting (no JWT plumbing here):
--   SET app.tenant_id = 1;
-- Tests must run as lab_user (admin is superuser and bypasses RLS).

CREATE SCHEMA IF NOT EXISTS lab;

CREATE TABLE IF NOT EXISTS lab.documents (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id INT NOT NULL,
    body TEXT NOT NULL
);

-- Helper: current tenant from session setting, NULL when unset (fail-closed).
CREATE OR REPLACE FUNCTION lab.current_tenant() RETURNS INT
LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('app.tenant_id', true), '')::int
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'lab_user'
    ) THEN
        CREATE ROLE lab_user NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA lab TO lab_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON lab.documents TO lab_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lab TO lab_user;

ALTER TABLE lab.documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON lab.documents;
CREATE POLICY tenant_isolation ON lab.documents
    FOR ALL TO lab_user
    USING (tenant_id = lab.current_tenant())
    WITH CHECK (tenant_id = lab.current_tenant());

-- Seed two tenants. Owner bypasses RLS, so plain INSERT works here.
INSERT INTO lab.documents (tenant_id, body) VALUES
    (1, 't1-doc-a'),
    (1, 't1-doc-b'),
    (2, 't2-doc-a')
ON CONFLICT DO NOTHING;
