-- Realtime source table: every insert fires a NOTIFY with the row
-- as JSON payload. Listeners (Go SSE server next) fan out per tenant.

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.events (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id INT NOT NULL,
    kind TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION app.notify_event() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM pg_notify('events', row_to_json(NEW)::text);

    RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS events_notify ON app.events;
CREATE TRIGGER events_notify
    AFTER INSERT ON app.events
    FOR EACH ROW
    EXECUTE FUNCTION app.notify_event();

-- Seed one row per tenant so streams are non-empty on boot.
INSERT INTO app.events (tenant_id, kind, payload) VALUES
    (1, 'seed', '{"msg":"tenant 1 online"}'),
    (2, 'seed', '{"msg":"tenant 2 online"}')
ON CONFLICT DO NOTHING;
