CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.todos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    task TEXT NOT NULL,
    due TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'web_anon'
    ) THEN
        CREATE ROLE web_anon NOLOGIN;
    END IF;
END
$$;

-- Authenticator role must exist before PostgREST boots.
-- Password is injected via docker-compose env (default: mysecretpassword).
-- DO block keeps `migrate up` idempotent on re-runs.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'authenticator'
    ) THEN
        CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'mysecretpassword';
    END IF;
END
$$;

GRANT web_anon TO authenticator;

GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.todos TO web_anon;
-- Needed for GENERATED ... AS IDENTITY primary key on POST.
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA api TO web_anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA api
    GRANT USAGE, SELECT ON SEQUENCES TO web_anon;
