CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.todos (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    done BOOLEAN NOT NULL DEFAULT FALSE,
    task TEXT NOT NULL,
    due TIMESTAMPTZ
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_roles WHERE rolname = 'web_anon'
    ) THEN
        CREATE ROLE web_anon NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA api TO web_anon;
GRANT SELECT ON api.todos TO web_anon;

create role authenticator noinherit login password 'mysecretpassword';
grant web_anon to authenticator;
