name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  verify:
    name: make-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run make check (tidy, vet, build, test)
        run: make check

  lint-check:
    name: golangci-lint-v2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout 5m --config .golangci.yml
          version: v2.6.2

  secret-scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Scan secrets
        run: docker run --rm -v ${{ github.workspace }}:/repo zricethezav/gitleaks:latest detect --source /repo -v
